<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('application/default', array('controller' => 'Newregister', 'action' => 'addnewregister')));
$form->setAttribute('method', 'post');
?>
            
<div class="main_header">Lägg till nytt register</div>
<div class="content_view">

	<?php echo $this->form()->openTag($form) ?>

        <?php echo $this->formInput($form->get('reg_name')) ?>
        <?php echo $this->formInput($form->get('reg_desc')) ?>
        <?php echo $this->formInput($form->get('submit')) ?>

	<?php echo $this->form()->closeTag() ?>

</div>

